config/routes.rb
Classvote::Application.routes.draw do
  
  root :to => "choices#index"
  
  resources :choices, :except => [:destroy] do
    member do
      get :vote
    end
  end
  
  resource :session, :only => [:new, :create]
  
  match "logout", :to => "sessions#destroy"

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  
  has_many :votes
  
  validates_presence_of :title, :allow_blank => false
  
  attr_accessible :title, :description, :url, :votes_count
  
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  
  belongs_to :choice, :counter_cache => true
  
  validates_presence_of :student_id_number
  validates_presence_of :choice_id
  
  validate :three_vote_limit
  
  attr_accessible :choice_id
  
  #Turns 1234567890 into "xxxxxxx890"
  def mask
    sid = student_id_number.to_s
    
    len = sid.length - 3
    exes = ""
    len.times {exes << "x"}
      
    sid.gsub /\A.{#{len}}/, exes
  end
  
  private
  def three_vote_limit
    count = Vote.where("student_id_number = ?", self.student_id_number).count
    
    if count >= 3
      self.errors.add :student_id_number, " has already voted 3 times"
    end
  end 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :set_current_student
  
  private
  def set_current_student
    @current_student = session[:student_id_number]
  end
  
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  
  before_filter :require_student, :only => :vote
  
  def vote
    v = Vote.new(:choice_id => params[:id])
    v.student_id_number = @current_student.to_i
    
    if v.valid?
      v.save!
      flash[:notice] = "Thanks for the vote"
    else
      flash[:error] = "You can't vote anymore"
    end
    redirect_to root_url
  end
  
  # GET /choices
  # GET /choices.xml
  def index
    @choices = Choice.order("votes_count DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @choices }
    end
  end

  # GET /choices/1
  # GET /choices/1.xml
  def show
    @choice = Choice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @choice }
    end
  end

  # GET /choices/new
  # GET /choices/new.xml
  def new
    @choice = Choice.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @choice }
    end
  end

  # GET /choices/1/edit
  def edit
    @choice = Choice.find(params[:id])
  end

  # POST /choices
  # POST /choices.xml
  def create
    @choice = Choice.new(params[:choice])

    respond_to do |format|
      if @choice.save
        format.html { redirect_to(@choice, :notice => 'Choice was successfully created.') }
        format.xml  { render :xml => @choice, :status => :created, :location => @choice }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @choice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /choices/1
  # PUT /choices/1.xml
  def update
    @choice = Choice.find(params[:id])

    respond_to do |format|
      if @choice.update_attributes(params[:choice])
        format.html { redirect_to(@choice, :notice => 'Choice was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @choice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.xml
  def destroy
    @choice = Choice.find(params[:id])
    @choice.destroy

    respond_to do |format|
      format.html { redirect_to(choices_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  def require_student
    unless @current_student.to_i > 0
      flash[:error] = "Log in first bro"
      redirect_to root_path
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  
  def new
  end
  
  def create
  end
  
  def destroy
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    cookie_session params[:session][:student_id_number]
    redirect_to root_url
  end
  
  def destroy
    cookie_session nil
    redirect_to root_url
  end
  
  private 
  def cookie_session(student_id_number)
    cookies[:student_id_number] = student_id_number
    session[:student_id_number] = student_id_number
    @current_student = student_id_number
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def current_vote_count
    Vote.where("student_id_number = ?", @current_student).count
  end
  
  def votes_left
    3 - current_vote_count
  end
  
  def valid_tags
    %w(a p strong em b ul ol li)
  end
  
  def super_sanitize(dirty)
    sanitize(dirty, :tags => valid_tags, :attributes=>"href")
  end
  
end

app/helpers/choices_helper.rb
module ChoicesHelper
  
  def can_vote_on(choice)
    unless @current_student.nil?
      current_vote_count < 3
    end
  end
  
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/choices/_form.html.erb
<%= semantic_form_for(@choice) do |form| %>
  <%= form.inputs do %>
    <%= form.input :title, :as => :string %>
    <%= form.input :description, :as => :text, :label => "Papers" %>
  <% end %>
  <%= form.inputs do %>
    <%= form.commit_button %>
  <% end %>
<% end %>

<p>
  You can use the following html tags: <%= valid_tags.to_sentence %>
</p>

app/views/choices/edit.html.erb
<h1>Editing <%= @choice.title %></h1>

<% if @choice.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

    <ul>
    <% @choice.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form' %>

<%= link_to 'Show', @choice %> |
<%= link_to 'Back', choices_path %>

app/views/choices/index.html.erb
<strong><%= link_to 'Add a new CHI2011 Session', new_choice_path %></strong>
&nbsp;&nbsp;|&nbsp;&nbsp;<strong><%= link_to 'Find more CHI2011 Sessions', "http://portalparts.acm.org/1980000/1978942/fm/frontmatter.pdf" %></strong>

<%= link_to 'Expand All Details', "#", :id => "expand_all", :style=>"float:right"%>

<% @choices.each do |choice| %>
  <%= div_for choice, :class => "drop-shadow lifted" do %>
    <table>
      <tr>
        <td class="votes">
            <% if can_vote_on choice %>
              <h2 class="vote_button">
                <%= link_to raw('&#x25B2;'), vote_choice_url(choice), :id => "vote_#{choice.id}", :title => "Vote for #{choice.title}" %>
              </h2>
              <h2 class="vote_count">
                <%= link_to choice.votes_count, vote_choice_url(choice), :title => "Vote for #{choice.title}" %>
              </h2>
            <% else %>
              &#x25B2;
              <h2 class="vote_count"><%= choice.votes_count %></h2>
            <% end %>
          </td>
        <td class="title"><h1><%= choice.title %></h1></td>
        <td class="details">
          <%= link_to 'Details', "#choice_#{choice.id}", :class => "toggle_details" %>
        </td>
      </tr>
    </table>
    
    <div class="details">
      <p>
        <b>Papers:</b>
      </p>
      <p>
        <%= choice.description.html_safe %>
      </p>

      <p>
        <b>Voters:</b>
        <ul>
          <% choice.votes.all.each do |v| %>
            <li><%= "#{v.mask} at #{v.created_at.strftime("%l:%M%p %d %b")}" %></li>
          <% end %>
        </ul>
      </p>
    </div>
  <% end %>
<% end %>

<% content_for(:jquery) do %>
  $(".toggle_details").click(function(event){
    $(this).parents("div").children("div").slideToggle();
  })
  $("#expand_all").click(function(){
    $("div.details").slideToggle();
  })
<% end %>

app/views/choices/new.html.erb
<h1>New Session</h1>

<%= render 'form' %>

<%= link_to 'Back', choices_path %>

app/views/choices/show.html.erb
<p>
  <b>Title:</b>
  <%= @choice.title %>
</p>

<p>
  <b>Description:</b>
  <%= super_sanitize @choice.description %>
</p>

<p>
  <b>Voters:</b>
  <ul>
    <% @choice.votes.all.each do |v| %>
      <li><%= "#{v.mask} at #{v.created_at.strftime("%l:%M%p %d %b")}" %></li>
    <% end %>
  </ul>
</p>


<%= link_to 'Edit', edit_choice_path(@choice) %> |
<%= link_to 'Back', choices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classvote</title>
  <%= stylesheet_link_tag "scaffold", "960", "formtastic", "formtastic_changes", "style" %>
  <%= javascript_include_tag "jquery-1.6.1.min" %>
  <%= csrf_meta_tag %>
</head>
<body>
  
  <div class="header">
    <div class="container12">
      <div class="grid6 title">
        <%= link_to "CHI 2011 Session Chooser", root_url %>
      </div>
      <div class="grid6 login">
        <%= render "sessions/login" %> 
      </div>
    </div>
  </div>
  


<div class="container12">

  <% if flash[:error] || flash[:notice] %>
    <section class="grid12">
      <% if flash[:error] %>
        <p style="font-weight: bold; color:#A00"><%= flash[:error] %></p>
      <% end %>
      <% if flash[:notice] %>
        <p style="font-weight: bold; color:#0A0"><%= flash[:notice] %></p>
      <% end %>
    </section>
  <% end %>

  <section class="grid12">
    <%= yield %>
  </section>
  
  <section class="grid12">
    <p>
      <strong><%= link_to "About this app", "#about", :id=>"about_toggle" %></strong>
    </p>
    <div id="about" style="display:none">
      <p>Created by Nick Malcolm</p>
      <p>w: <%= link_to "itsnickmalcolm.com", "http://itsnickmalcolm.com" %></p>
      <p>t: <%= link_to "@nickmalcolm", "http://twitter.com/nickmalcolm" %></p>
      <p><%= link_to "View Source", "http://github.com/nickmalcolm/classvote" %></p>
      <p>This was more fun than reddit...</p>
    </div>
  </section>
    

</div>

<script>
$(document).ready(
  function(){
    <%= content_for(:jquery) %>
    
    $("#about_toggle").click(function(){
      $("#about").slideToggle();
    })
  });
</script>

</body>
</html>